### ISSUE TITLE
Build failed on head Ruby and 6.1 Rails.

### ISSUE THREAD

**Issue by yamat47** [yamat47/activerecord_accessible_json#17]
https://github.com/yamat47/activerecord_accessible_json/actions/runs/1247277159

**Comment by yamat47** [comment]
```
┏╸..activerecord_accessible_json · ⎇ main⟳  ‹✚1…1› · 🏷 v0.3.8
┗╸❯❯❯ bundle exec rspec --backtrace

An error occurred while loading ./spec/activerecord_accessible_json/json_extension_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

ArgumentError:
  wrong number of arguments (given 1, expected 0)
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:657:in `initialize'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:657:in `new'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:657:in `block in register_class_with_precision'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/type/type_map.rb:54:in `perform_fetch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/type/type_map.rb:21:in `block in fetch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/map.rb:203:in `block in fetch_or_store'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/map.rb:182:in `fetch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/map.rb:202:in `fetch_or_store'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/type/type_map.rb:20:in `fetch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/type/type_map.rb:16:in `lookup'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/quoting.rb:214:in `lookup_cast_type'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1456:in `fetch_type_metadata'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/sqlite3/schema_statements.rb:140:in `new_column_from_field'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:117:in `block in columns'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `map'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:111:in `fetch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:120:in `block in columns_hash'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:119:in `fetch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:119:in `columns_hash'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/model_schema.rb:553:in `load_schema!'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/attributes.rb:250:in `load_schema!'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/model_schema.rb:539:in `block in load_schema'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/model_schema.rb:536:in `synchronize'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/model_schema.rb:536:in `load_schema'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/model_schema.rb:402:in `attribute_types'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/model_schema.rb:428:in `type_for_attribute'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/type_caster/map.rb:16:in `type_for_attribute'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/arel/table.rb:108:in `type_for_attribute'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/table_metadata.rb:18:in `type'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:63:in `build'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:58:in `[]'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:131:in `block in expand_from_hash'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:84:in `each'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:84:in `flat_map'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:84:in `expand_from_hash'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/predicate_builder.rb:29:in `build_from_hash'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/query_methods.rb:1091:in `build_where_clause'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/query_methods.rb:645:in `where!'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/relation/query_methods.rb:640:in `where'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/querying.rb:22:in `where'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/internal_metadata.rb:39:in `[]'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/tasks/database_tasks.rb:357:in `schema_up_to_date?'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:633:in `block in load_schema_if_pending!'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:632:in `all?'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:632:in `load_schema_if_pending!'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:653:in `block in maintain_test_schema!'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:906:in `suppress_messages'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:658:in `method_missing'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:653:in `maintain_test_schema!'
# ./spec/rails_helper.rb:30:in `<top (required)>'
# ./spec/activerecord_accessible_json/json_extension_spec.rb:3:in `require'
# ./spec/activerecord_accessible_json/json_extension_spec.rb:3:in `<top (required)>'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load_file_handling_errors'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1615:in `block in load_spec_files'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `each'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `load_spec_files'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:102:in `setup'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/bin/rspec:25:in `load'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/bin/rspec:25:in `<top (required)>'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/cli.rb:478:in `exec'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/bundler-2.3.0.dev/libexec/bundle:49:in `block in <top (required)>'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/bundler-2.3.0.dev/libexec/bundle:37:in `<top (required)>'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/bin/bundle:23:in `load'
# /Users/yamat47/.rbenv/versions/3.1.0-dev/bin/bundle:23:in `<main>'
No examples found.


Finished in 0.00003 seconds (files took 0.73394 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by yamat47** [comment]
Ruby 3.1+ does not work with Rails 7-. CI condition combinations are updated.
